# Generated by Django 5.1.4 on 2024-12-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('media_urls', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
